#!/usr/bin/bash
# Hook: Session Startup Validation
# Event: SessionStart (startup|resume)
# Purpose: Enforces CLAUDE.md startup checklist by reading TASKS.md, JOURNAL.md,
#          SECURITY.md, and .claude/tasks/*.md, then injecting context.

INPUT=$(cat)
PROJECT_DIR=$(echo "$INPUT" | node -e "process.stdin.resume();let d='';process.stdin.on('data',c=>d+=c);process.stdin.on('end',()=>console.log(JSON.parse(d).cwd||''))")

echo "=== SESSION STARTUP CHECKLIST (Auto-Generated by Hook) ==="
echo ""

# 1. Check TASKS.md for IN_PROGRESS or BLOCKED tasks
TASKS_FILE="$PROJECT_DIR/TASKS.md"
if [ -f "$TASKS_FILE" ]; then
  IN_PROGRESS=$(grep -i "IN_PROGRESS" "$TASKS_FILE" 2>/dev/null | head -5)
  BLOCKED=$(grep -i "BLOCKED" "$TASKS_FILE" 2>/dev/null | head -5)
  if [ -n "$IN_PROGRESS" ] || [ -n "$BLOCKED" ]; then
    echo "[TASKS.md] Active tasks found:"
    if [ -n "$IN_PROGRESS" ]; then
      echo "$IN_PROGRESS" | while IFS= read -r line; do echo "  IN_PROGRESS: $line"; done
    fi
    if [ -n "$BLOCKED" ]; then
      echo "$BLOCKED" | while IFS= read -r line; do echo "  BLOCKED: $line"; done
    fi
  else
    echo "[TASKS.md] No IN_PROGRESS or BLOCKED tasks."
  fi
else
  echo "[TASKS.md] File not found - no task tracking active."
fi

# 2. Check .claude/tasks/*.md for orchestration state
TASKS_DIR="$PROJECT_DIR/.claude/tasks"
if [ -d "$TASKS_DIR" ]; then
  TASK_FILES=$(ls -1 "$TASKS_DIR"/*.md 2>/dev/null)
  if [ -n "$TASK_FILES" ]; then
    COUNT=$(echo "$TASK_FILES" | wc -l | tr -d ' ')
    echo ""
    echo "[.claude/tasks/] $COUNT orchestration file(s) found:"
    echo "$TASK_FILES" | tail -3 | while IFS= read -r tf; do
      BASENAME=$(basename "$tf")
      PREVIEW=$(head -5 "$tf" 2>/dev/null | tr '\n' ' ' | cut -c1-200)
      echo "  - $BASENAME: $PREVIEW"
    done
  else
    echo ""
    echo "[.claude/tasks/] No orchestration files."
  fi
else
  echo ""
  echo "[.claude/tasks/] Directory not found."
fi

# 3. Read last entries from JOURNAL.md
JOURNAL_FILE="$PROJECT_DIR/JOURNAL.md"
if [ -f "$JOURNAL_FILE" ]; then
  # Extract last 2 section headers (## lines) with a few lines of context
  LAST_ENTRIES=$(grep -n "^## " "$JOURNAL_FILE" | tail -2)
  if [ -n "$LAST_ENTRIES" ]; then
    echo ""
    echo "[JOURNAL.md] Last 2 entries:"
    echo "$LAST_ENTRIES" | while IFS=: read -r lineno rest; do
      PREVIEW=$(sed -n "${lineno},$((lineno+3))p" "$JOURNAL_FILE" 2>/dev/null | tr '\n' ' ' | cut -c1-300)
      echo "  - $PREVIEW"
    done
  else
    echo ""
    echo "[JOURNAL.md] No entries found."
  fi
else
  echo ""
  echo "[JOURNAL.md] File not found."
fi

# 4. Check SECURITY.md for critical unresolved findings
SECURITY_FILE="$PROJECT_DIR/SECURITY.md"
if [ -f "$SECURITY_FILE" ]; then
  CRITICAL_LINES=$(grep -i "critical\|high" "$SECURITY_FILE" | grep -iv "resolved" | head -5)
  if [ -n "$CRITICAL_LINES" ]; then
    COUNT=$(echo "$CRITICAL_LINES" | wc -l | tr -d ' ')
    echo ""
    echo "[SECURITY.md] WARNING - $COUNT unresolved critical/high finding(s):"
    echo "$CRITICAL_LINES" | while IFS= read -r line; do
      echo "  - $(echo "$line" | cut -c1-200)"
    done
  else
    echo ""
    echo "[SECURITY.md] No unresolved critical/high findings."
  fi
else
  echo ""
  echo "[SECURITY.md] File not found."
fi

echo ""
echo "=== END STARTUP CHECKLIST ==="

exit 0
